#!/usr/bin/env python

from urllib2 import urlopen
import re
from sys import argv
from datetime import datetime
from statsdb import StatsDB

if len(argv) < 2:
    print "Usage: " + argv[0] + " <dbfile>"
    exit(1)

DB_FILE = argv[1]
CURRENT_TIME = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
URLS_FILE = 'bubok.urls'

urls = [line.strip() for line in open(URLS_FILE)]

db = StatsDB(DB_FILE)

DB_TABLE = 'book_downloads'
db.init_table(DB_TABLE, ['title', '#downloads', 'time'])

for url in urls:
    html = urlopen(url).read()

    title_regex = re.compile('<h1 itemprop="name">(.+)</h1>')
    downloads_regex = re.compile(">Descargas:</span> ([0-9]+)")

    title = ''
    match = title_regex.search(html)
    if match:
        title = match.group(1)
    else:
        print "Error reading title from URL"
        exit(1)

    downloads = 0
    match = downloads_regex.search(html)
    if match:
        downloads = int(match.group(1))
    else:
        print "Error reading downloads from URL"
        exit(1)

    db.insert(DB_TABLE, (title, downloads, CURRENT_TIME))

db.save()
