#!/usr/bin/env python

from urllib2 import urlopen
from simplejson import loads
from sys import argv
from datetime import datetime
from statsdb import StatsDB

if len(argv) < 2:
    print "Usage: " + argv[0] + " <dbfile>"
    exit(1)

DB_FILE = argv[1]
URL = 'http://graph.facebook.com/473881175964178'
CURRENT_TIME = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

content = loads(urlopen(URL).read())

likes = content['likes']
talking = content['talking_about_count']

db = StatsDB(DB_FILE)

DB_TABLE = 'fb_likes'
db.init_table(DB_TABLE, ['#likes', 'time'])
db.insert(DB_TABLE, (DB_TABLE1, likes, CURRENT_TIME), norepeat={'likes': likes})


DB_TABLE = 'fb_talking'
db.init_table(DB_TABLE, ['#talking', 'time'])
db.insert(DB_TABLE, (DB_TABLE, talking, CURRENT_TIME), norepeat={'talking': talking})


db.save()
