#!/bin/bash

PATH=$1

DB="${PATH}/stats.db"

TABLE=$2

if [ -x "$TABLE" ]
then
    echo "Usage: $0 <table>"
fi

OUTFILE="${PATH}/${TABLE}.csv"

sqlite3 $DB <<EOF
.headers off
.mode csv
.output $OUTFILE
select * from $TABLE;
EOF

sed -i 's/"//g' $OUTFILE
