#!/bin/bash

DB="stats.db"

PATH1=$1

cd $PATH1

TABLE=$2

if [ -x "$TABLE" ]
then
echo "Usage: $0 <table>"
fi

OUTFILE="${TABLE}.csv"

sqlite3 $DB <<EOF
.headers off
.mode csv
.output $OUTFILE
select * from $TABLE;
EOF

sed -i 's/"//g' $OUTFILE


