#!/usr/bin/env python

from twython import Twython
from sys import argv
from datetime import datetime
from statsdb import StatsDB

if len(argv) < 3:
    print "Usage: " + argv[0] + " <twitter.keys>" + " <dbfile>"
    exit(1)

KEY_FILE = argv[1]

with open(KEY_FILE) as f:
    APP_KEY = f.readline().strip("\n")
    APP_SECRET = f.readline().strip("\n")

DB_FILE = argv[2]
CURRENT_TIME = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

twitter = Twython(APP_KEY, APP_SECRET)
auth = twitter.get_authentication_tokens()

OAUTH_TOKEN = auth['oauth_token']
OAUTH_TOKEN_SECRET = auth['oauth_token_secret']

is_error = False
done = False

db = StatsDB(DB_FILE)
db.init_table('tw_followers', ['name','#followers', 'time'])
db.init_table('tw_statuses', ['name','#statuses', 'time'])

while not done:
    try:
        response = twitter.show_user(screen_name = "partido_x")
    except TwythonRateLimitError:
        is_error = True
    except TwythonError:
        is_error = True
    if is_error:
        print 'error: waiting for 60 seconds'
        sleep(60)
    else:
        followers = response['followers_count']
        DB_TABLE = 'tw_followers'
        db.insert(DB_TABLE, (DB_TABLE, followers, CURRENT_TIME), norepeat={'followers': followers})
        
        
        statuses = response['tw_statuses']
        DB_TABLE = 'tw_statuses'
        db.insert(DB_TABLE, (DB_TABLE, followers, CURRENT_TIME), norepeat={'statuses': statuses})
        
        done = True

db.save()
