#!/usr/bin/env python

from twython import Twython
from sys import argv
from datetime import datetime
from statsdb import StatsDB

if len(argv) < 2:
    print "Usage: " + argv[0] + " <dbfile>"
    exit(1)

APP_KEY = " "
APP_SECRET = " "

DB_FILE = argv[1]
CURRENT_TIME = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

twitter = Twython(APP_KEY, APP_SECRET)
auth = twitter.get_authentication_tokens()

OAUTH_TOKEN = auth['oauth_token']
OAUTH_TOKEN_SECRET = auth['oauth_token_secret']

is_error = False
done = False

db = StatsDB(DB_FILE)
db.init_table('tw_followers', ['#followers', 'time'])
db.init_table('tw_statuses', ['#statuses', 'time'])

while not done:
    try:
        response = twitter.show_user(screen_name = "partido_x")
    except TwythonRateLimitError:
        is_error = True
    except TwythonError:
        is_error = True
    if is_error:
        print 'error: waiting for 60 seconds'
        sleep(60)
    else:
        followers = response['followers_count']
        statuses = response['statuses_count']
        db.insert('tw_followers', (followers, CURRENT_TIME), norepeat={'followers': followers})
        db.insert('tw_statuses', (statuses, CURRENT_TIME), norepeat={'statuses': statuses})
        done = True

db.save()
