#!/usr/bin/python
# coding: utf-8

from fb_utils import get_json, get_access_keys_from_file, get_access_token_from_file


(FACEBOOK_APP_ID, FACEBOOK_APP_SECRET) = get_access_keys_from_file()
accessToken = get_access_token_from_file()
print accessToken

userId = '473881175964178'

task = 'page_impressions_by_age_gender_unique/day'

sexes = ['M', 'F']
ages = ['18-24', '25-34', '35-44', '45-54', '55-64', '65+']

categories = []
for age in ages:
    for sex in sexes:
        categories = categories + [sex + '.' + age]
print categories


name = task[5:-11]
print name
url = 'https://graph.facebook.com/' + userId + '/insights/' + task + '?access_token=' + accessToken

print url
insights = get_json(url)

count = 0


def extract_insights(insights, categories):
    vtext = []
    for ins in insights['data'][0]['values']:
        day = ins['end_time']
        values = [0] * len(categories)
        for i in range(len(categories)):
            if categories[i] in ins['value']:
                values[i] = ins['value'][categories[i]]
        values_str = ''
        for v in values:
            values_str = values_str + ',' + str(v)
        vtext = [(day + values_str + '\n').encode('utf8')] + vtext

    for text in vtext:
        f.write(text)
        print text[0:15]

f = open('page_insights.csv', 'w')

categories_str = ''
for cat in categories:
    categories_str = categories_str + ',' + cat
f.write(('date' + categories_str + '\n').encode('utf8'))

extract_insights(insights, categories)

while 'previous' in insights['paging']:
    url = insights['paging']['previous']
    insights = get_json(url)
    count += 1
    extract_insights(insights, categories)
