#!/usr/bin/env python

from selenium import webdriver
from sys import argv
from time import sleep, time

NUM_TRIES = 5

driver = None


# USE FOR DEBUG
def screenshot(driver):
    png = driver.get_screenshot_as_png()
    filename = 'foto' + str(time()) + '.png'
    with open(filename, 'w') as fp:
        fp.write(png)
    print 'Saved', filename


def get_token(login_email, login_password):
    global driver
    driver.get('https://developers.facebook.com/tools/explorer')

    email = driver.find_element_by_id('email')
    email.click()
    email.send_keys(login_email)
    password = driver.find_element_by_id('pass')
    password.click()
    password.send_keys(login_password)
    driver.find_element_by_name('login').click()
    sleep(1)

    driver.find_element_by_id('get_access_token').click()
    sleep(1)
    driver.find_element_by_link_text('Extended Permissions').click()
#    driver.find_element_by_link_text('Clear').click()
    driver.find_element_by_name('read_insights').click()
    driver.find_element_by_xpath(".//button[contains(.,'Get Access Token')]").click()

    timeout = 100
    # Wait until new window pops up
    while (len(driver.window_handles) < 2) and (timeout > 0):
        sleep(0.1)
        timeout -= 1
    driver.switch_to_window(driver.window_handles[-1])

    # Wait until popup is closed
    while (len(driver.window_handles) > 1) and (timeout > 0):
        driver.find_element_by_xpath(".//button[contains(.,'Aceptar')]").click()
        sleep(0.1)
        timeout -= 1
    driver.switch_to_window(driver.window_handles[0])

    element = driver.find_element_by_xpath(".//input[@id='access_token']")
    return element.get_attribute('value')

if __name__ == "__main__":
    if len(argv) == 3:
        for i in range(NUM_TRIES):
            driver = webdriver.PhantomJS()
            driver.implicitly_wait(5)
            try:
                token = get_token(argv[1], argv[2])
                if token:
                    print "ACCESS TOKEN: " + token
                    f = open('fb.token', 'w')
                    f.write(token)
                    f.close()
                    break
                else:
                    print "Empty token, retrying..."
            except Exception, e:
                print str(e)
                print "Attempt failed, retrying..."
            driver.quit()
    else:
        print "Usage: " + argv[0] + " <login> <password>"
        exit(1)
